### PR TITLE
Fix bug with inserting links and undoing things.

### LINKED ISSUE #98: Undoing bug after using toolbar icons
Causes unusual behavior in the editor. Start with the following content in the editor:

```
# Test
This is a test
```

Steps to reproduce:
1. Place cursor at very end of content
2. Click the link button
3. Undo (Cmd-Z or Ctrl-Z)
4. At this point, it requires two backspaces to do anything.
5. Click the image button
6. Undo
7. At this point, a single character is not removed from the undo.
8. Additionally, if you press the backspace key, the entire line is deleted.

My guess is that it's an issue with CodeMirror, but we'll need to find it and correct it.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #98.
Generally reproducing the problem was much less complex than described in the issue, you just needed to click 'Insert link' and then undo, and repeat this at least once.

The problem inside the code was tricky, we creat two variables like so:

``` javascript
var startPoint = cm.getCursor("start");
var endPoint = cm.getCursor("end");
```

But as `getCursor` returns an object  they just points to objects stored probably somewhere in the CodeMirror!
Then we have:

``` javascript
startPoint.ch += start.length;
```

Which increments the cursor position which surely isn't stored in the history of the editor so calling `undo` doesn't moves this back (as in the case of `setSelection` or `setCursor` CodeMirror functions).

[Here's the demo](https://jsfiddle.net/zc38r4w2/).

### CODE REVIEW

**Comment by WesCossick** [comment]
Thanks, that one was annoying.

File: src/js/simplemde.js [hunk 1]
```diff
@@ -795,8 +795,9 @@ function _replaceSelection(cm, active, startEnd, url) {
 	var text;
 	var start = startEnd[0];
 	var end = startEnd[1];
-	var startPoint = cm.getCursor("start");
-	var endPoint = cm.getCursor("end");
+	var startPoint = {}, endPoint = {};
+	Object.assign(startPoint, cm.getCursor("start"));
```
Comment (AbijeetP) [inline src/js/simplemde.js:799]: Unfortunately this causes issues with IE 11, which does not support `Object.assign` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

Comment (jonatanklosko) [reply src/js/simplemde.js:799]: Should be as easy as adding a polyfill dependency to this lib.

Comment (AbijeetP) [reply src/js/simplemde.js:799]: Yup, added the polyfill mentioned on the MDN website, and things started working.
